### ISSUE TITLE
Stats are odd

### ISSUE THREAD

**Issue by iammaxc** [FSInvestments/ListManagement#50]
True Stats for the following: 66 in list, 40 found, 26 found in FINRA and created.

Search results:
Total Advisors: 66
Found in SF: 66
Updating Contact in SF or Adding to Campaign: 40 Contact Info Up-To-Date: 0
Creating: 26
Added to Campaign or BDG: 40
Updated in Campaign or Stayed in BDG: 0
Removed from Campaign or BDG: 0
Need Research: -26
Received: 2016-09-08 15:02:32
Process Started: 2016-09-08 11:20:05
Process Completed: 2016-09-08 11:21:50
Processing Time: 0 days 0 hours 1 minutes 45 seconds

**Comment by rickyschoolsFS** [comment]
@iammaxc - I'm clearly an idiot. When I wrote the update for stats last week, i was writing a statement completely wrong. I'd point out the location of the ']' below. 

Should be fixed. Resync when you ge to the office.

I wrote:
        num = len(df[df['ContactID' != '']])

should be:
        num = len(df[df['ContactID'] != ''])
